export const ADD_ARTICLE = 'ADD_ARTICLE'
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE'
export const SET_ARTICLES = 'SET_ARTICLES'
export const ADD_USER = 'ADD_USER'
export const REMOVE_USER = 'REMOVE_USER'
